org: serverlessguru
app: patterns
service: examplea

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-2"}
  # profile: serverlessguru

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ../webpack.config.js   # Name of webpack configuration file
    # includeModules: true

functions:
  hello:
    handler: src/functions/handler.hello