service: sls-eventbridge
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  scheduledService:
    handler: handler.scheduledService
    events:
      - eventBridge:
          schedule: rate(1 minute)

  invoiceService:
    handler: handler.invoiceService
    events:
      - eventBridge:
          pattern:
            detail:
              operation:
                - invoice-service

  rewardService:
    handler: handler.rewardService
    events:
      - eventBridge:
          pattern:
            detail:
              operation:
                - reward-service