service: webpack-refactor

plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
  - serverless-appsync-plugin
  - serverless-offline
package:
  individually: true
  exclude:
    - ./**

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, "us-east-2"}
  stage: ${opt:stage, "int"}

custom:
  appSync:
    name: webpack-refactor
    authenticationType: API_KEY
    mappingTemplatesLocation: src/mapping-templates
    mappingTemplates: 
      - dataSource: Retrieve 
        type: Query 
        field: retrieve
        request: request.vtl
        response: response.vtl
      - dataSource: serviceA 
        type: Query 
        field: serviceA
        request: request.vtl
        response: response.vtl
      - dataSource: serviceB 
        type: Query 
        field: serviceB
        request: request.vtl
        response: response.vtl
      - dataSource: serviceC 
        type: Query 
        field: serviceC
        request: request.vtl
        response: response.vtl
      - dataSource: serviceD 
        type: Query 
        field: serviceD
        request: request.vtl
        response: response.vtl

    dataSources:
      - type: AWS_LAMBDA
        name: Retrieve 
        description: retreive
        config:
          functionName: appsync-${opt:stage, "dev"}
          lambdaFunctionArn: { "Fn::GetAtt": ["RetrieveLambdaFunction", "Arn" ] }
      - type: AWS_LAMBDA
        name: serviceA 
        description: retreive
        config:
          functionName: appsync-serviceA-${opt:stage, "dev"}
          lambdaFunctionArn: { "Fn::GetAtt": ["ServiceALambdaFunction", "Arn" ] }
      - type: AWS_LAMBDA
        name: serviceB
        description: retreive
        config:
          functionName: appsync-serviceB-${opt:stage, "dev"}
          lambdaFunctionArn: { "Fn::GetAtt": ["ServiceBLambdaFunction", "Arn" ] }
      - type: AWS_LAMBDA
        name: serviceC 
        description: retreive
        config:
          functionName: appsync-serviceC-${opt:stage, "dev"}
          lambdaFunctionArn: { "Fn::GetAtt": ["ServiceCLambdaFunction", "Arn" ] }
      - type: AWS_LAMBDA
        name: serviceD 
        description: retreive
        config:
          functionName: appsync-serviceD-${opt:stage, "dev"}
          lambdaFunctionArn: { "Fn::GetAtt": ["ServiceDLambdaFunction", "Arn" ] }

functions:
  Retrieve:
    handler: src/handlers/query/src/index.handler 
    package:
      include:
        - src/handlers/commonfiles/**
        - src/handlers/query/**
  
  serviceA:
    handler: src/handlers/serviceA/index.handler
    package:
      include:
        - src/handlers/commonfiles/**
        - src/handlers/serviceA/**

  serviceB:
    handler: src/handlers/serviceB/src/index.handler
    package:
      include:
        - src/handlers/commonfiles/**
        - src/handlers/serviceB/**

  serviceC:
    handler: src/handlers/serviceC/index.handler
    package:
      include:
        - src/handlers/commonfiles/**
        - src/handlers/serviceC/**
 
  serviceD:
    handler: src/handlers/serviceD/index.handler
    package:
      include:
        - src/handlers/commonfiles/**
        - src/handlers/serviceD/**
 