org: serverlessguru
app: patterns
service: example1

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-2"}

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  hello:
    name: my-lambda-function-${self:provider.stage}
    handler: index.handler
    #environment:
      #API_KEY: ${param:API_KEY}

#outputs:
  #lambdaName: my-lambda-function-${self:provider.stage}
