# org: serverlessguru
# app: patterns
service: example-lambda-test-logs
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-2"}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:putObject
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ELKExampleS3Bucket"
            - "/*"
        
custom:
  base: ${self:service}-${self:provider.stage}
  bucketName: ${self:custom.base}-bucket
  layerStackName: elk-lambda-extension-test-logs-${self:provider.stage}

functions:
  # Lambda that has ELK Extension attached
  example:
    name: ${self:custom.base}-exampleLambda
    handler: src/handlers/example.handler
    events:
      - http:
          path: /example
          cors: true
          method: any
    environment:
      REGION: ${self:provider.region}
      EXTENSION_LOG_DESTINATIONS: "s3"
      EXTENSION_LOG_DESTINATION_S3_BUCKET_NAME: ${self:custom.bucketName}
      EXTENSION_LOG_DESTINATION_S3_OBJECT_NAME: ${self:custom.base}-exampleLambda
    layers:
      - ${cf:${self:custom.layerStackName}.ELKLambdaExtensionLayerLambdaLayerQualifiedArn}

resources:
  Resources:
    ELKExampleS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}