version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo installing deps
      - npm install
      - echo installing angular cli
      - npm i -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
      - aws s3 rm s3://${BUCKET}/ --recursive
      - aws s3 cp ./dist/frontend s3://${BUCKET}/ --recursive --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers