name: Dev Deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # Install Dependencies
    - run: npm i serverless -g
    - run: npm i
    - run: sls config credentials --provider aws --key ${{secrets.DEV_AWS_KEY}} --secret ${{secrets.DEV_AWS_SECRET}}
    - run: (cd resources/route53/hostedZone && sls deploy --stage dev --region us-west-2 -v)
    - run: (cd resources/artifacts && sls deploy --stage dev --region us-west-2 -v)
    - run: (cd resources/route53/cert && sls deploy --stage dev --region us-west-2 -v)
    - run: (cd resources/cognito && sls deploy --stage dev --region us-west-2 -v)
    - run: (cd resources/api && sls deploy --stage dev --region us-west-2 -v)
    - run: (cd services/auth && sls deploy --stage dev --region us-west-2 -v)
