dev:
  COGNITO_USERPOOL_ID: xyz
  COGNITO_USERPOOL_REGION: xyz
  COGNITO_USER_POOL_ARN: xyz
qa:
  COGNITO_USERPOOL_ID: xyz
  COGNITO_USERPOOL_REGION: xyz
  COGNITO_USER_POOL_ARN: xyz
prod:
  COGNITO_USERPOOL_ID: xyz
  COGNITO_USERPOOL_REGION: xyz
  COGNITO_USER_POOL_ARN: xyz